// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dot': string;
  'hidden': string;
  'hover': string;
  'pen': string;
}
export const cssExports: CssExports;
export default cssExports;
